//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrilleLoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journee
    {
        public Journee()
        {
            this.Parties = new HashSet<Partie>();
        }
    
        public int Id { get; set; }
        public string Num { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<Partie> Parties { get; set; }
    }
}
