//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrilleLoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        public int Id { get; set; }
        public int Num { get; set; }
        public int Partie_Id { get; set; }
    
        public virtual Partie Partie { get; set; }
    }
}
